apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    project: k8spatterns
    pattern: sidecar
spec:
  containers:
  - name: app
    image: centos/httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/www/html
      name: source
  - name: poll
    image: bitnami/git
    env:
    - name: SOURCE_REPO
      value: https://github.com/mdn/beginner-html-site-scripted
    command: ["sh", "-c"]
    args:
    - |
      git clone $(SOURCE_REPO) .
      while true; do
        sleep 60
        git pull
      done
    workingDir: /var/lib/data
    volumeMounts:
    - mountPath: /var/lib/data
      name: source
  volumes:
  - emptyDir: {}
    name: source
---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: k8spatterns
    pattern: sidecar
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    pattern: sidecar
  type: NodePort