apiVersion: v1
kind: Service
metadata:
  name: bluegreen-test-svc
spec:
  selector:
    app: bluegreen-test
    color: blue
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort