apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - name: nodejs
        image: luksa/kubia:v1
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-svc
spec:
  type: NodePort
  selector:
    app: kubia
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080