apiVersion: v1
kind: Pod
metadata:
  name: resource-consumer-pod
spec:
  containers:
  - name: resource-consumer
    image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
  - name: busybox-sidecar
    image: busybox:stable
    command: ['sh' '-c', 'until curl localhost:8080/ConsumeCPU -d "millicors=100&durationSec=3600"; do sleep 5; done && while true; do sleep 10; done']