apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  strategy:
    type: RollingUpdate #[Recreate, RollingUpdate]
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      contianers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort:80:
