apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
spec:
  ttlSecondsAfterFinished: 100
  completions: 12
  parallelism: 3
  backoffLimit: 4
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never # [Never, OnFailure]
