apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-test-group
  namespace: resources-test
spec:
  hard:
    requests.memory: 128Mi
    requests.cpu: 500m
    limits.memory: 256Mi
    limits.cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: too-many-resources-pod
  image: busybox:stable
  command: ['sh', '-c', 'while true; do echo running...; sleep 5; done']
  resources:
    requests: 
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 200Mi
      cpu: 500m