apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  namespace: resources-test
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; echo running...; sleep 5; done']
    resources:
      requests:
        memory: 128Mi
        cpu: 500m
      limits:
        memory: 256Mi
        cpu: 500m