apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
  labels:
    app: gitrepo-volume-pod
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/luksa/kubia-website-example.git
      revision: master
      directory: .
---
apiVersion: v1
kind: Service
metadata:
  name: gitrepo-volume-pod-service
spec:
  selector:
    app: gitrepo-volume-pod
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort



